version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.sun.mail:jakarta.mail
        versions: "[2.0.0,)"
      - dependency-name: jakarta.activation:jakarta.activation-api
        versions: "[2.0.0,)"
      - dependency-name: jakarta.mail:jakarta.mail-api
        versions: "[2.0.0,)"
